Update action.yml

diff --git a/.github/actions/info/action.yml b/.github/actions/info/action.yml
--- a/.github/actions/info/action.yml
+++ b/.github/actions/info/action.yml
@@ -140,56 +140,35 @@ runs:
         # Solution Project Value
         ################################################################################
         echo "::group::● Solution Project Value"
-        if [ -f "solution_project_value.result" ]; then
-          cat "solution_project_value.result"
-        else
-          echo "::Warning::⚠️ File not found: solution_project_value.result"
-        fi
+        cat "solution_project_value.result" || echo "::Warning::⚠️ File not found or cannot read: solution_project_value.result"
         echo "::groupend::"
 
         ################################################################################
         # Deploy Value
         ################################################################################
         echo "::group::● Deploy Value"
-        if [ -f "deploy_value.result" ]; then
-          cat "deploy_value.result"
-        else
-          echo "::Warning::⚠️ File not found: deploy_value.result"
-        fi
+        cat "deploy_value.result" || echo "::Warning::⚠️ File not found or cannot read: deploy_value.result"
         echo "::groupend::"
 
         ################################################################################
         # Git Value
         ################################################################################
         echo "::group::● Git Value"
-        if [ -f "git-value.result" ]; then
-          cat "git_value.result"
-        else
-          echo "::Warning::⚠️ File not found: git_value.result"
-        fi
+        cat "git-value.result" || echo "::Warning::⚠️ File not found or cannot read: git_value.result"
         echo "::groupend::"
 
         ################################################################################
         # Exist Files
         ################################################################################
         echo "::group::● Exist Files"
-        if [ -f "exist_files.result" ]; then
-          cat "exist_files.result"
-        else
-          echo "::Warning::⚠️ File not found: exist_files.result"
-        fi
-        cat exist_files.result
+        cat "exist_files.result" || echo "::Warning::⚠️ File not found or cannot read: exist_files.result"
         echo "::groupend::"
 
         ################################################################################
         # Git Info
         ################################################################################
         echo "::group::● Git Info"
-        if [ -f "git_info.result" ]; then
-          cat "git_info.result"
-        else
-          echo "::Warning::⚠️ File not found: git_info.result"
-        fi
+        cat "git_info.result" || echo "::Warning::⚠️ File not found or cannot read: git_info.result"
         echo "::groupend::"
       shell: bash
       continue-on-error: true
