Update action.yml

diff --git a/.github/actions/info/action.yml b/.github/actions/info/action.yml
--- a/.github/actions/info/action.yml
+++ b/.github/actions/info/action.yml
@@ -49,10 +49,23 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Check jp Command
+      run: |
+        if ! command -v jp &> /dev/null; then
+          echo -e "\033[31m[Error] 'jp' command is not installed or not in PATH.\033[0m"
+          echo -e "\033[33m[Hint] Please install 'jp' before running this workflow.\033[0m"
+          exit 1
+        else
+          echo -e "\033[32m[Success] 'jp' command is available.\033[0m"
+        fi
+      shell: bash
+
     - name: Add Execute Permission for Scripts
       run: |
         echo Add Execute Permission for Scripts
-        chmod +x ./.scripts/check/*.sh
+        chmod +x ./.scripts/check/values.sh
+        chmod +x ./.scripts/check/exist-files.sh
+        chmod +x ./.scripts/check/git-info.sh
       shell: bash
 
     - name: Check Solution & Project Values
@@ -125,13 +138,13 @@ runs:
     - name: Remove Execute Permission for Scripts
       run: |
         echo Remove Execute Permission for Scripts
-        chmod -x ./.scripts/check/*.sh
+        chmod -x ./.scripts/check/values.sh
+        chmod -x ./.scripts/check/exist-files.sh
+        chmod -x ./.scripts/check/git-info.sh
       shell: bash
 
     - name: Output  Logs
       run: |
-        TEXT_DEFAULT_COLOR="\033[38;5;245m"
-        RESET="\033[0m"
         echo " "
         echo " "
         echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────┐\033[0m\
