Update ci-action.yml

diff --git a/.github/workflows/ci-action.yml b/.github/workflows/ci-action.yml
--- a/.github/workflows/ci-action.yml
+++ b/.github/workflows/ci-action.yml
@@ -82,6 +82,39 @@ jobs:
           exit 1
         fi
 
+
+
+  build:
+    name: Build Project
+    runs-on: ubuntu-latest
+    needs: start-ci
+    strategy:
+      matrix:
+        configuration: [Debug, Release]
+
+        
+    steps:
+
+    - name: Checkout Code
+      uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
+
+    - name: Check Directory
+      run: |
+        echo "Current directory: $(pwd)"
+        echo "Listing all files and directories:"
+        ls -R
+  
+    - name: Verify Solution File
+      run: |
+        if [ -f "SimpleFileIO.sln" ]; then
+          echo "Solution file found: SimpleFileIO.sln"
+        else
+          echo "Error: SimpleFileIO.sln not found."
+          exit 1
+        fi
+
     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
@@ -89,32 +122,6 @@ jobs:
 
     - name: Restore dependencies
       run: dotnet restore SimpleFileIO.sln --verbosity detailed
-        # # if [ -f "SimpleFileIO.sln" ]; then
-        #   echo "Solution file found: SimpleFileIO.sln"
-        #   dotnet restore SimpleFileIO.sln
-        # else
-        #   echo "Error: SimpleFileIO.sln not found in current directory."
-        #   exit 1
-        # fi
-    - name: Upload Setup Artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: setup-artifacts
-        path: .
-
-  build:
-    name: Build Project
-    runs-on: ubuntu-latest
-    needs: setup
-    strategy:
-      matrix:
-        configuration: [Debug, Release]
-
-    steps:
-    - name: Download Setup Artifacts
-      uses: actions/download-artifact@v4
-      with:
-        name: setup-artifacts
 
     - name: Build ${{ matrix.configuration }} Configuration
       run: |
