Update ci-action.yml

diff --git a/.github/workflows/ci-action.yml b/.github/workflows/ci-action.yml
--- a/.github/workflows/ci-action.yml
+++ b/.github/workflows/ci-action.yml
@@ -35,7 +35,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: start-ci
     steps:
-    - name: Check Directory
+    - name: Before Directory
       run: |
         echo "Current directory: $(pwd)"
         echo "Listing all files and directories:"
@@ -44,6 +44,12 @@ jobs:
       uses: actions/checkout@v4
       with:
         fetch-depth: 0  # 전체 이력 가져오기
+
+    - name: After Directory
+      run: |
+        echo "Current directory: $(pwd)"
+        echo "Listing all files and directories:"
+        ls -R
 
   setup:
     name: Setup
@@ -56,13 +62,22 @@ jobs:
         echo "Listing all files and directories:"
         ls -R
 
+    - name: Verify Solution File
+      run: |
+        if [ -f "SimpleFileIO.sln" ]; then
+          echo "Solution file found: SimpleFileIO.sln"
+        else
+          echo "Error: SimpleFileIO.sln not found."
+          exit 1
+        fi
+
     - name: Setup .NET
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: '8.0.x'
 
     - name: Restore dependencies
-      run: dotnet restore SimpleFileIO.sln
+      run: dotnet restore SimpleFileIO.sln -verbosity detailed
         # # if [ -f "SimpleFileIO.sln" ]; then
         #   echo "Solution file found: SimpleFileIO.sln"
         #   dotnet restore SimpleFileIO.sln
