Update main-push-ci-cd.yml

diff --git a/.github/workflows/main-push-ci-cd.yml b/.github/workflows/main-push-ci-cd.yml
--- a/.github/workflows/main-push-ci-cd.yml
+++ b/.github/workflows/main-push-ci-cd.yml
@@ -94,7 +94,8 @@ jobs:
       - name: To File Output
         run: |
           # To File Output
-          echo "${{ steps.dll-build-test.outputs.result }}" || echo "::Warning::⚠️ Invalid Build Validation Result" > ./${{ runner.os }}/${{ matrix.configuration }}/build_validation.result
+          echo "${{ steps.dll-build-test.outputs.result }}" || echo "::Warning::⚠️ Invalid Build Validation Result" > "./${{ runner.os }}/${{ matrix.configuration }}/build_validation.result"
+        shell: bash
 
       - uses: actions/upload-artifact@v4
         with:
