Update main-push-ci-cd.yml

diff --git a/.github/workflows/main-push-ci-cd.yml b/.github/workflows/main-push-ci-cd.yml
--- a/.github/workflows/main-push-ci-cd.yml
+++ b/.github/workflows/main-push-ci-cd.yml
@@ -76,11 +76,19 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Dll Build Test
+        id: dll-build-test
         uses: ./.github/actions/build-validation/dotnet
         with:
           project_file_path: "${{vars.DLL_PROJECT_FILE_PATH}}"
           build_configuration: "${{matrix.configuration}}"
           dotnet_version: "${{ vars.DOTNET_VERSION }}"
+      - name: Check Output
+        run: |
+          echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────────────────────────┐\033[0m"
+          printf "\033[38;5;245m|\033[38;5;15m  %-76s\033[38;5;245m│\033[0m\n" "Build Validation"
+          echo -e "\033[38;5;245m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
+          echo "${{ steps.dll-build-test.outputs.result }}" || echo "::Warning::⚠️ Invalid Build Validation Result"
+
 
       - uses: actions/upload-artifact@v4
         with:
