Update main-push-ci-cd.yml

diff --git a/.github/workflows/main-push-ci-cd.yml b/.github/workflows/main-push-ci-cd.yml
--- a/.github/workflows/main-push-ci-cd.yml
+++ b/.github/workflows/main-push-ci-cd.yml
@@ -55,15 +55,15 @@ jobs:
           echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────────────────────────┐\033[0m"
           printf "\033[38;5;245m|\033[38;5;15m  %-76s\033[38;5;245m│\033[0m\n" "Else Value"
           echo -e "\033[38;5;245m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
-          echo "${{ steps.info-and-check.outputs.else_value_result }}" || echo "::Warning::⚠️ Invalid Else Value Result"
+          echo -e "${{ steps.info-and-check.outputs.else_value_result }}" || echo "::Warning::⚠️ Invalid Else Value Result"
           echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────────────────────────┐\033[0m"
           printf "\033[38;5;245m|\033[38;5;15m  %-76s\033[38;5;245m│\033[0m\n" "Exist Files"
           echo -e "\033[38;5;245m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
-          echo "${{ steps.info-and-check.outputs.exist_files_result }}" || echo "::Warning::⚠️ Invalid Exist Files Result"
+          echo -e "${{ steps.info-and-check.outputs.exist_files_result }}" || echo "::Warning::⚠️ Invalid Exist Files Result"
           echo -e "\033[38;5;245m┌──────────────────────────────────────────────────────────────────────────────┐\033[0m"
           printf "\033[38;5;245m|\033[38;5;15m  %-76s\033[38;5;245m│\033[0m\n" "Git Info"
           echo -e "\033[38;5;245m└──────────────────────────────────────────────────────────────────────────────┘\033[0m"
-          echo "${{ steps.info-and-check.outputs.git_info_result }}" || echo "::Warning::⚠️ Invalid Git Info Result"
+          echo -e "${{ steps.info-and-check.outputs.git_info_result }}" || echo "::Warning::⚠️ Invalid Git Info Result"
 
   build-validation:
     name: Build Validation
@@ -142,11 +142,6 @@ jobs:
       - uses: actions/checkout@v4
       - uses: actions/download-artifact@v4
         with:
-            name: Info
-            path: ./results/info
-        continue-on-error: true
-      - uses: actions/download-artifact@v4
-        with:
             name: Build_Validation_Linux_Debug
             path: ./results/build_validation/linux/debug
         continue-on-error: true
@@ -166,73 +161,43 @@ jobs:
             path: ./results/build_validation/windows/release
         continue-on-error: true
 
-      - name: Merge Value Results
+      - name: Make Info Result Files
         run: |
-          # Merge Value Results
+          # Make Info Result Files
 
-          ################################################################################
-          # Create Temp file
-          ################################################################################
+          # Set directory
+          if [ ! -d "./results/info/" ]; then
+              mkdir -p "./results/info/"
+          fi
+
+          # Git Info
+          echo -e ${{ needs.info-and-check.outputs.git_info_result }} > ./results/info/git_info.result
+
+          # Exist Files
+          echo -e ${{ needs.info-and-check.outputs.exist_files_result }} > ./results/info/exist_files.result
+
+          # Values
           temp_file=$(mktemp)
-
-          ################################################################################
-          # Apply Solution Project Value
-          ################################################################################
-          if [ -f ./results/info/solution_project_value.result ]; then
-            echo -e "\033[38;5;245m● Solution & Project\033[0m" >> $temp_file
-            awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' ./results/info/solution_project_value.result >> $temp_file
+          echo -e "\033[38;5;245m● Solution & Project\033[0m" >> "$temp_file"
+          if [[ -z "${{ needs.info-and-check.outputs.solution_project_value_result }}" ]]; then
+            echo -e "\033[38;5;245m⚠️ Empty Solution And Project Value Result\033[0m" >> "$temp_file"
           else
-            echo -e "\033[48;5;52m\033[38;5;196mFile not found: ./results/info/solution_project_value.result\033[0m" >> $temp_file
-            echo -e "\033[48;5;52m\033[38;5;196mFile not found: ./results/info/solution_project_value.result\033[0m"
+            echo "${{ needs.info-and-check.outputs.solution_project_value_result }}" | awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' >> "$temp_file"
           fi
-          
-          ################################################################################
-          # Apply Git Value
-          ################################################################################
-          if [ -f ./results/info/git_value.result ]; then
-          echo -e "\033[38;5;245m● Git\033[0m" >> $temp_file
-          awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' ./results/info/git_value.result >> $temp_file
+          echo -e "\033[38;5;245m● Git\033[0m" >> "$temp_file"
+          if [[ -z "${{ needs.info-and-check.outputs.git_value_result }}" ]]; then
+            echo -e "\033[38;5;245m⚠️ Empty Git Value Result\033[0m" >> "$temp_file"
           else
-          echo -e "\033[48;5;52m\033[38;5;196mFile not found: ./results/info/git_value.result\033[0m" >> $temp_file
-          echo -e "\033[48;5;52m\033[38;5;196mFile not found: ./results/info/git_value.result\033[0m"
+            echo "${{ needs.info-and-check.outputs.git_value_result }}" | awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' >> "$temp_file"
           fi
-
-          ################################################################################
-          # Apply Else Value
-          ################################################################################
-          if [ -f ./results/info/else_value.result ]; then
-            echo -e "\033[38;5;245m● Else\033[0m" >> $temp_file
-            awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' ./results/info/else_value.result >> $temp_file
+          echo -e "\033[38;5;245m● Else\033[0m" >> "$temp_file"
+          if [[ -z "${{ needs.info-and-check.outputs.else_value_result }}" ]]; then
+            echo -e "\033[38;5;245m⚠️ Empty Else Value Result\033[0m" >> "$temp_file"
           else
-            echo -e "\033[48;5;52m\033[38;5;196mFile not found: ./results/info/else_value.result\033[0m" >> $temp_file
-            echo -e "\033[48;5;52m\033[38;5;196mFile not found: ./results/info/else_value.result\033[0m"
+            echo "${{ needs.info-and-check.outputs.else_value_result }}" | awk '{printf "\033[38;5;245m - %s\033[0m\n", $0}' >> "$temp_file"
           fi
-          
-          ################################################################################
-          # Ensure result file directory exists
-          ################################################################################
-          merge_result=./results/info/value.result
-          result_dir=$(dirname "$merge_result")
-          if [ ! -d "$result_dir" ]; then
-              mkdir -p "$result_dir"
-          fi
-          cp "${temp_file}" "${merge_result}"
-
-          ################################################################################
-          # Delete temp file
-          ################################################################################
+          cp "${temp_file}" "./results/info/value.result"
           rm -f "$temp_file"
-
-          ################################################################################
-          # Debug
-          ################################################################################
-          if [ "${{ env.result_to_console }}" = "true" ]; then
-          echo -e "\033[48;5;241m\033[38;5;15mDebug : ${merge_result}\033[0m"
-          cat $merge_result
-          fi
-          
-        env:
-          result_to_console: false
         continue-on-error: true
 
       - name: Sermary
